### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by qveezzx** [Sphere-Systems/SphereOS#10]
Errors like "no definition "weight"/"height" ", Plugins dont want to install (i installed cosmos dev tools), no dlls like "SphereOS.dll", "NextCore.Graphics.dll" and more.

**Comment by Jspa2** [comment]
Hello, could you confirm that you are using a current build of the Cosmos Dev Kit, rather than the User Kit? The issues about the Width/Height properties that you mention sound like signs of an outdated version of Cosmos.

**Comment by qveezzx** [comment]
> Hello, could you confirm that you are using a current build of the Cosmos Dev Kit, rather than the User Kit? The issues about the Width/Height properties that you mention sound like signs of an outdated version of Cosmos.

How can i check it?

**Comment by Jspa2** [comment]
> > Hello, could you confirm that you are using a current build of the Cosmos Dev Kit, rather than the User Kit? The issues about the Width/Height properties that you mention sound like signs of an outdated version of Cosmos.
> 
> How can i check it? also could you provide me latest cosmos? I dont know if i have latest one.

If you downloaded Cosmos from its releases section on GitHub, then you're using the user kit. Otherwise, if you cloned its repo and built it manually, you're using the dev kit.

I recommend you follow this guide, then try building SphereOS again:
https://cosmosos.github.io/install.html#dev-kit

**Comment by qveezzx** [comment]
![image](https://user-images.githubusercontent.com/120045358/219676800-80dc62bf-1013-48e5-8e52-26004cb68a3f.png)
Sorry for asking but im new to Cosmos, i need to drag these files to C:\Source or the SphereOS dir?

**Comment by qveezzx** [comment]
> > > Hello, could you confirm that you are using a current build of the Cosmos Dev Kit, rather than the User Kit? The issues about the Width/Height properties that you mention sound like signs of an outdated version of Cosmos.
> > 
> > 
> > How can i check it? also could you provide me latest cosmos? I dont know if i have latest one.
> 
> If you downloaded Cosmos from its releases section on GitHub, then you're using the user kit. Otherwise, if you cloned its repo and built it manually, you're using the dev kit.
> 
> I recommend you follow this guide, then try building SphereOS again: https://cosmosos.github.io/install.html#dev-kit

i did everything what was in instructions but still gettings errors 
„IOPortBase.Write32(ushort, uint)”
"cant convert from ushort to unit[]"
still "Height" and "Width" problem

**Comment by qveezzx** [comment]
fixed it, thanks for help (i didnt changed to compile "SphereOS"

**Comment by qveezzx** [comment]
![image](https://user-images.githubusercontent.com/120045358/219687046-487f5430-ca2a-412b-8f70-9c2485ab5786.png)
i fixed it but theres two errors, how to fix them please
