### ISSUE TITLE
CodeStudio

### ISSUE THREAD

**Issue by qveezzx** [Sphere-Systems/SphereOS#11]
Sorry for opening next issue but when i want to register CodeStudio i get this:
Type or namespace 'CodeStudio' is not created in namespace 'SphereOS.Gui.Apps' (are you missing an assembly reference?)

**Comment by Jspa2** [comment]
CodeStudio is a WIP, it does not work fully yet. Therefore its code files are excluded from the build.

If you want to test it, then in the VS solution explorer you can set the type of every .cs file in the CodeStudio directory to 'C# Compiler' (they are currently 'None').
